name: 'import bio.tools'
description: 'bio.tools bulk import'
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'bio.tools'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
      #shell: bash
    - name: Install dependencies
      run:
        pip install -r ${{ github.action_path }}/../scripts/biotools-import/requirements.txt
      shell: bash
    - name: debug with ls
      run: |
        ls ${{ github.workspace }}
      shell: bash
    - name: debug with cd/pwd
      run: |
        cd ${{ github.workspace }}
        pwd
      shell: bash
    - name: import bio.tools using the API
      run: |
        cd ${{ github.workspace }}/content/data
        if ${{ github.action_path }}/../scripts/git-utils/checkout-pr-if-exist.sh biotools-import; then
          IS_PR_CREATED=true
        else
          IS_PR_CREATED=false
        fi
        cd ${{ github.action_path }}/../scripts/biotools-import
        python import.py
        echo "IS_PR_CREATED=$IS_PR_CREATED" >> $GITHUB_ENV
      shell: bash
#    - name: commit new data and push to PR
#      env:
#        GITHUB_USER: ${{ secrets.GITHUB_USER }}
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      run: |
#        cd ${{ github.workspace }}/content/data
#        ${{ github.action_path }}/../scripts/git-utils/import-changes.sh $IS_PR_CREATED biotools-import
#      shell: bash
