name: 'import bio.tools'
description: 'bio.tools bulk import'
#inputs:
#  who-to-greet:  # id of input
#    description: 'Who to greet'
#    required: true
#    default: 'bio.tools'
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
      #shell: bash
    - name: Install dependencies
      run:
        pip install -r ${{ github.action_path }}/../scripts/biotools-import/requirements.txt
      shell: bash
    - name: import bio.tools using the API
      run: |
        if ${{ github.action_path }}/../scripts/git-utils/checkout-pr-if-exist.sh biotools-import; then
          IS_PR_CREATED=true
        else
          IS_PR_CREATED=false
        fi
        python ${{ github.action_path }}/../scripts/biotools-import/import.py
        echo "IS_PR_CREATED=$IS_PR_CREATED" >> $GITHUB_ENV
      shell: bash
    - name: reformat json to a predictable format with jq
      run: |
        FILES='data/*/*.biotools.json'
        for f in $FILES; do jq --indent 4 'walk( if type == "array" then sort else . end )'  $f | sponge $f; echo "processed $f file!"; done
      shell: bash
    - name: commit new data and push to PR
      env:
        GITHUB_USER: ${{ secrets.GITHUB_USER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ${{ github.action_path }}/../scripts/git-utils/import-changes.sh $IS_PR_CREATED biotools-import
      shell: bash
