name: 'import bioconda'
description: 'bioconda bulk import'
inputs:
  repo-user:  # id of input
    description: 'User that commits modifications'
    required: true
  repo-token:
    description: 'GitHub token to commit modifications'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"
    - uses: actions/checkout@v3
      with:
        repository: bioconda/bioconda-recipes
        path: /tmp/bioconda
    - name: Install dependencies
      run:
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: import bioconda tools
      run: |
        python3 ${{ github.action_path }}/bioconda_importer.py data/ /tmp/bioconda/recipes/
      shell: bash
