name: 'import bioconda'
description: 'bioconda bulk import'
inputs:
  repo-user:  # id of input
    description: 'User that commits modifications'
    required: true
  repo-token:
    description: 'GitHub token to commit modifications'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: download bioconda recipes
      run: |
        cd /tmp
        wget -O bioconda-recipes.zip https://codeload.github.com/bioconda/bioconda-recipes/zip/master
        unzip bioconda-recipes.zip
        rm bioconda-recipes.zip
      shell: bash
    - name: Install dependencies
      run:
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: import bioconda tools
      run: |
        python3 ${{ github.action_path }}/bioconda_importer.py . /tmp/bioconda-recipes-master/recipes/
      shell: bash
