name: 'import biocontainers'
description: 'biocontainers bulk import'
inputs:
  repo-user:  # id of input
    description: 'User that commits modifications'
    required: true
  repo-token:
    description: 'GitHub token to commit modifications'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run:
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - name: import biocontainers using the API
      run: |
        python3 ${{ github.action_path }}/biocontainers-importer.py ${{ github.workspace }}/data/ "https://raw.githubusercontent.com/BioContainers/tools-metadata/master/annotations.yaml"
      shell: bash
